[package]
name = "Talos"
edition = "2024" # Using latest Move 2024 features
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
Pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", subdir = "target_chains/sui/contracts", rev = "main" }
Wormhole = { git = "https://github.com/wormhole-foundation/wormhole.git", subdir = "sui/wormhole", rev = "main" }

[addresses]
talos = "0x0"
pyth = "0x00b53b0f4174108627fbee72e2498b58d6a2714cded53fac537034c220d26302" # Pyth Testnet (Verify current)
wormhole = "0x31358d198147da50db32eda2562951d53973a0c0ad5ed738e9b17d88b213d790" # Wormhole Testnet
